repos:
  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.12.0
    hooks:
    - id: markdownlint
  - repo: https://github.com/shellcheck-py/shellcheck-py.git
    rev: v0.9.0.2
    hooks:
    - id: shellcheck
      args:
      - --check-sourced
      - --shell=sh
      - --severity=style
      - --external-sources
  # Hooks from this repo:
  - repo: local
    hooks:
    - id: check-encoding
      name: Check encoding
      language: script
      entry: src/sh/check_encoding.sh -a us-ascii -a utf-8
      types: [text]